#just for tac
statistics=true
job=LoadSilver
jobVersion=0.1
date=2026-01-16 141909812
contextName=Default
jobId=_SOocUM-eEfCT24E9_qvxLA
jobType=Standard
framework=
projectId=0
applyContextToChildren=false
project=PROJECT
branch=branches/
cmdLineVersion=8.0.1.20211109_1610
gitAuthor=
gitCommitId=
gitCommitDate=