#this is context properties
#Fri Jan 16 16:27:05 CET 2026
kaggle_dataset=/opt/data/recipes_data.csv
letter=a
mongodb_authentificationDatabase=admin
mongodb_collection_bronze_k=episaine_bronze_k
mongodb_collection_bronze_tmdb=episaine_bronze_tmdb
mongodb_collection_silver=episaine_silver
mongodb_database=episaine
mongodb_password=root
mongodb_port=27017
mongodb_server=192.168.248.165
mongodb_user=root
postgresql_database=episaine
postgresql_password=episaine
postgresql_port=5433
postgresql_schema=gold
postgresql_server=192.168.248.170
postgresql_table_area=area
postgresql_table_category=category
postgresql_table_meals=meals
postgresql_user=episaine
source=https\://www.themealdb.com/api/json/v1/1/search.php?f\=
