spring.datasource.url=jdbc:postgresql://localhost:5432/episaine
spring.datasource.username=episaine
spring.datasource.password=episaine

#TODO: change to real values
spring.data.redis.host=localhost
spring.data.redis.port=6379