spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/episaine}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:episaine}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:episaine}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}