services:
  talend:
    image: eclipse-temurin:17-jdk
    container_name: talend
    tty: true
    stdin_open: true
    volumes:
      - ./Jobs:/opt/talend
      - ./Jobs/LoadBronze/project/loadbronze_0_1/contexts:/opt/talend/LoadBronze/project/loadbronze_0_1/contexts
      - ./Jobs/LoadSilver/project/loadsilver_0_1/contexts:/opt/talend/LoadSilver/project/loadsilver_0_1/contexts
      - ./Jobs/LoadGold/project/loadgold_0_1/contexts:/opt/talend/LoadGold/project/loadgold_0_1/contexts
      - ./recipes_data.csv:/opt/data/recipes_data.csv
    networks:
      - episaine-network

networks:
  episaine-network:
    external: true