services:
  talend:
    image: eclipse-temurin:17-jdk
    container_name: talend
    tty: true
    stdin_open: true
    volumes:
      - ./Jobs:/opt/talend
      - ./Jobs/LoadBronze/proto/loadbronze_0_1/contexts:/opt/talend/LoadBronze/proto/loadbronze_0_1/contexts
      - ./Jobs/LoadSilver/proto/loadsilver_0_1/contexts:/opt/talend/LoadSilver/proto/loadsilver_0_1/contexts
      - ./Jobs/LoadGold/proto/loadgold_0_1/contexts:/opt/talend/LoadGold/proto/loadgold_0_1/contexts
      - ./students.csv:/opt/data/students.csv
    networks:
      - episaine-network

networks:
  episaine-network:
    external: true