services:
  episaine-cache-loader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: episaine-cache-loader
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: master
      SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.248.170:5432/episaine
      SPRING_DATASOURCE_USERNAME: episaine
      SPRING_DATASOURCE_PASSWORD: episaine
      SPRING_DATA_REDIS_HOST: 192.168.248.105
      SPRING_DATA_REDIS_PORT: 6379